// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/installation/gen_types.mdx?collection=docs&hash=1758725047250"
import * as docs_5 from "../content/docs/components/trigger-button.mdx?collection=docs&hash=1758725047250"
import * as docs_4 from "../content/docs/components/light.mdx?collection=docs&hash=1758725047250"
import * as docs_3 from "../content/docs/components/camera.mdx?collection=docs&hash=1758725047250"
import * as docs_2 from "../content/docs/auth/setup.mdx?collection=docs&hash=1758725047250"
import * as docs_1 from "../content/docs/(root)/about.mdx?collection=docs&hash=1758725047250"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1758725047250"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"F:/Repos/ha-components/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"(root)\\about.mdx","absolutePath":"F:/Repos/ha-components/content/docs/(root)/about.mdx"}, data: docs_1 }, { info: {"path":"auth\\setup.mdx","absolutePath":"F:/Repos/ha-components/content/docs/auth/setup.mdx"}, data: docs_2 }, { info: {"path":"components\\camera.mdx","absolutePath":"F:/Repos/ha-components/content/docs/components/camera.mdx"}, data: docs_3 }, { info: {"path":"components\\light.mdx","absolutePath":"F:/Repos/ha-components/content/docs/components/light.mdx"}, data: docs_4 }, { info: {"path":"components\\trigger-button.mdx","absolutePath":"F:/Repos/ha-components/content/docs/components/trigger-button.mdx"}, data: docs_5 }, { info: {"path":"installation\\gen_types.mdx","absolutePath":"F:/Repos/ha-components/content/docs/installation/gen_types.mdx"}, data: docs_6 }], [{"info":{"path":"meta.json","absolutePath":"F:/Repos/ha-components/content/docs/meta.json"},"data":{"pages":["---Introduction---","index","[Showcase](/docs/showcase)","...(root)","---Setup---","...installation","---Auth---","...auth","---Components---","...components"],"root":true}}])